theme: jekyll-theme-midnight
#remote_theme: pages-themes/minimal@v0.2.0
#theme: jekyll-theme-merlot
#theme: jekyll-theme-modernist
#theme: jekyll-theme-architect
#theme: jekyll-theme-minimal
#theme: jekyll-theme-cayman
#theme: jekyll-theme-slate
#theme: jekyll-theme-tactile
plugins:
- jekyll-remote-theme
title: FrameByFrameDebuggerDocs
google_analytics: [G-F8DRMS9PJ7]